//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalyzerDatabase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnalyzerDatabase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutResult {
            get {
                return ResourceManager.GetString("AboutResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract: .
        /// </summary>
        public static string AbstractDataGrid {
            get {
                return ResourceManager.GetString("AbstractDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount downloaded publications:.
        /// </summary>
        public static string AmountDownloadedPublications {
            get {
                return ResourceManager.GetString("AmountDownloadedPublications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount found duplicates:.
        /// </summary>
        public static string AmountFoundDuplicates {
            get {
                return ResourceManager.GetString("AmountFoundDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount inquiries to the database:.
        /// </summary>
        public static string AmountInquiries {
            get {
                return ResourceManager.GetString("AmountInquiries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Science Direct and Scopus.
        /// </summary>
        public static string ApiScienceAndScopusSettings {
            get {
                return ResourceManager.GetString("ApiScienceAndScopusSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Springer.
        /// </summary>
        public static string ApiSpringerSettings {
            get {
                return ResourceManager.GetString("ApiSpringerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors: .
        /// </summary>
        public static string AuthorDataGrid {
            get {
                return ResourceManager.GetString("AuthorDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string AuthorDataGridHeader {
            get {
                return ResourceManager.GetString("AuthorDataGridHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By authors.
        /// </summary>
        public static string ByAuthors {
            get {
                return ResourceManager.GetString("ByAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By magazine.
        /// </summary>
        public static string ByMagazine {
            get {
                return ResourceManager.GetString("ByMagazine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By publication.
        /// </summary>
        public static string ByPublication {
            get {
                return ResourceManager.GetString("ByPublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By year.
        /// </summary>
        public static string ByYear {
            get {
                return ResourceManager.GetString("ByYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the settings that you have typed API key for this database!.
        /// </summary>
        public static string CheckApiKey {
            get {
                return ResourceManager.GetString("CheckApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobalt.
        /// </summary>
        public static string CobaltColorSettings {
            get {
                return ResourceManager.GetString("CobaltColorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration API Key.
        /// </summary>
        public static string ConfigApiKeySettings {
            get {
                return ResourceManager.GetString("ConfigApiKeySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem communicating with the database..
        /// </summary>
        public static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of occurrences of a given year.
        /// </summary>
        public static string CountYear {
            get {
                return ResourceManager.GetString("CountYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default location to save the publication.
        /// </summary>
        public static string DefaultSavingLocationSettings {
            get {
                return ResourceManager.GetString("DefaultSavingLocationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOI:.
        /// </summary>
        public static string DoiDataGrid {
            get {
                return ResourceManager.GetString("DoiDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOI.
        /// </summary>
        public static string DoiDataGridHeader {
            get {
                return ResourceManager.GetString("DoiDataGridHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download publication.
        /// </summary>
        public static string DownloadPublication {
            get {
                return ResourceManager.GetString("DownloadPublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string Downloads {
            get {
                return ResourceManager.GetString("Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates.
        /// </summary>
        public static string Duplicates {
            get {
                return ResourceManager.GetString("Duplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem downloading the publication, try again in a moment..
        /// </summary>
        public static string ErrorDownloadPublication {
            get {
                return ResourceManager.GetString("ErrorDownloadPublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data from a full review to a .csv file.
        /// </summary>
        public static string ExportFullDataGrid {
            get {
                return ResourceManager.GetString("ExportFullDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data to a .csv file.
        /// </summary>
        public static string ExportToCsv {
            get {
                return ResourceManager.GetString("ExportToCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export chart data number 1 to .csv.
        /// </summary>
        public static string ExportToCsv1 {
            get {
                return ResourceManager.GetString("ExportToCsv1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export chart data number 2 to .csv.
        /// </summary>
        public static string ExportToCsv2 {
            get {
                return ResourceManager.GetString("ExportToCsv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export chart to .png.
        /// </summary>
        public static string ExportToPng {
            get {
                return ResourceManager.GetString("ExportToPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export chart number 1 to .png.
        /// </summary>
        public static string ExportToPng1 {
            get {
                return ResourceManager.GetString("ExportToPng1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export chart number 2 to .png.
        /// </summary>
        public static string ExportToPng2 {
            get {
                return ResourceManager.GetString("ExportToPng2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string FilterData {
            get {
                return ResourceManager.GetString("FilterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get API Key for Science Direct and Scopus databases.
        /// </summary>
        public static string GetApiKeyElsevier {
            get {
                return ResourceManager.GetString("GetApiKeyElsevier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get API Key for Springer database.
        /// </summary>
        public static string GetApiKeySpringer {
            get {
                return ResourceManager.GetString("GetApiKeySpringer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string GreenColorSettings {
            get {
                return ResourceManager.GetString("GreenColorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group after the name of the database.
        /// </summary>
        public static string GroupDatabase {
            get {
                return ResourceManager.GetString("GroupDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeMenu {
            get {
                return ResourceManager.GetString("HomeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indigo.
        /// </summary>
        public static string IndigoColorSettings {
            get {
                return ResourceManager.GetString("IndigoColorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        public static string InterfaceSettings {
            get {
                return ResourceManager.GetString("InterfaceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isbn: .
        /// </summary>
        public static string IsbnDataGrid {
            get {
                return ResourceManager.GetString("IsbnDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issn: .
        /// </summary>
        public static string IssnDataGrid {
            get {
                return ResourceManager.GetString("IssnDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue: .
        /// </summary>
        public static string IssueDataGrid {
            get {
                return ResourceManager.GetString("IssueDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageSettings {
            get {
                return ResourceManager.GetString("LanguageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazine.
        /// </summary>
        public static string Magazine {
            get {
                return ResourceManager.GetString("Magazine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name and surname.
        /// </summary>
        public static string NameAuthor {
            get {
                return ResourceManager.GetString("NameAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextBtn {
            get {
                return ResourceManager.GetString("NextBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to display, select the graph or table of data!.
        /// </summary>
        public static string NoDataToDisplay {
            get {
                return ResourceManager.GetString("NoDataToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to display, enter a search query!.
        /// </summary>
        public static string NoDataToDisplayInDataGrid {
            get {
                return ResourceManager.GetString("NoDataToDisplayInDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data to export!.
        /// </summary>
        public static string NoDataToExport {
            get {
                return ResourceManager.GetString("NoDataToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No access to the internet!.
        /// </summary>
        public static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not enter the search criteria!.
        /// </summary>
        public static string NotCriteria {
            get {
                return ResourceManager.GetString("NotCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not selected, none of the databases to be searched!.
        /// </summary>
        public static string NotSelectedDatabase {
            get {
                return ResourceManager.GetString("NotSelectedDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occured:.
        /// </summary>
        public static string Occurred {
            get {
                return ResourceManager.GetString("Occurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Access.
        /// </summary>
        public static string OpenAccessDataGrid {
            get {
                return ResourceManager.GetString("OpenAccessDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open containing folder.
        /// </summary>
        public static string OpenContainingFolder {
            get {
                return ResourceManager.GetString("OpenContainingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to open the exported file?.
        /// </summary>
        public static string OpenExportFile {
            get {
                return ResourceManager.GetString("OpenExportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall statistics.
        /// </summary>
        public static string OverallStatistics {
            get {
                return ResourceManager.GetString("OverallStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page range: .
        /// </summary>
        public static string PageRangeDataGrid {
            get {
                return ResourceManager.GetString("PageRangeDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pii: .
        /// </summary>
        public static string PiiDataGrid {
            get {
                return ResourceManager.GetString("PiiDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        public static string Polish {
            get {
                return ResourceManager.GetString("Polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string PrevBtn {
            get {
                return ResourceManager.GetString("PrevBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication date: .
        /// </summary>
        public static string PublicationDateDataGrid {
            get {
                return ResourceManager.GetString("PublicationDateDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication name:.
        /// </summary>
        public static string PublicationNameDataGrid {
            get {
                return ResourceManager.GetString("PublicationNameDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publications.
        /// </summary>
        public static string Publications {
            get {
                return ResourceManager.GetString("Publications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in database....
        /// </summary>
        public static string QueryText {
            get {
                return ResourceManager.GetString("QueryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received results.
        /// </summary>
        public static string ReceivedResultsTitleWindow {
            get {
                return ResourceManager.GetString("ReceivedResultsTitleWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshData {
            get {
                return ResourceManager.GetString("RefreshData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results in.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchMenu {
            get {
                return ResourceManager.GetString("SearchMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the database to search:.
        /// </summary>
        public static string SelectDatabase {
            get {
                return ResourceManager.GetString("SelectDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show chart for the page in the search engine.
        /// </summary>
        public static string ShowChart {
            get {
                return ResourceManager.GetString("ShowChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See chart for full review.
        /// </summary>
        public static string ShowChartFull {
            get {
                return ResourceManager.GetString("ShowChartFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show graph the amount of appeals to the bases.
        /// </summary>
        public static string ShowChartOverall1 {
            get {
                return ResourceManager.GetString("ShowChartOverall1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show graph number of downloads / duplicate.
        /// </summary>
        public static string ShowChartOverall2 {
            get {
                return ResourceManager.GetString("ShowChartOverall2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See details in the table for the page in the search engine.
        /// </summary>
        public static string ShowDataInTable {
            get {
                return ResourceManager.GetString("ShowDataInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See details in the table of the full review.
        /// </summary>
        public static string ShowDataInTableFull {
            get {
                return ResourceManager.GetString("ShowDataInTableFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the full list of existing data.
        /// </summary>
        public static string ShowFullListWithData {
            get {
                return ResourceManager.GetString("ShowFullListWithData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show groups of 25 results.
        /// </summary>
        public static string ShowGroupsResults {
            get {
                return ResourceManager.GetString("ShowGroupsResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more details.
        /// </summary>
        public static string ShowMoreDetailsToolTip {
            get {
                return ResourceManager.GetString("ShowMoreDetailsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source: .
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start on login.
        /// </summary>
        public static string StartOnLogin {
            get {
                return ResourceManager.GetString("StartOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string StatisticsMenu {
            get {
                return ResourceManager.GetString("StatisticsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style application.
        /// </summary>
        public static string StyleAppSettings {
            get {
                return ResourceManager.GetString("StyleAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum:.
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title: .
        /// </summary>
        public static string TitleDataGrid {
            get {
                return ResourceManager.GetString("TitleDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TitleDataGridHeader {
            get {
                return ResourceManager.GetString("TitleDataGridHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string TitleDialogError {
            get {
                return ResourceManager.GetString("TitleDialogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume: .
        /// </summary>
        public static string VolumeDataGrid {
            get {
                return ResourceManager.GetString("VolumeDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string YearRok {
            get {
                return ResourceManager.GetString("YearRok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
